baseURL = 'https://jamieroszel22.github.io/my_blog/'
publishDir = 'docs'
languageCode = 'en-us'
title = 'Project Workbench'
theme = 'ananke'


[params]
  description = "A technical log tracking software projects, dev experiments, and engineering insights."
  background_color_class = "bg-black"
  featured_image = "/images/project_workbench_hero.jpg"
  site_logo = "/images/project_workbench_logo.jpg"
  
[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1